leopardproject/urls.py
from django.conf.urls import  include, url
from leopard.views import * 
from django.contrib import admin
# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'leopardproject.views.home', name='home'),
    # url(r'^leopardproject/', include('leopardproject.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^admin/', include(admin.site.urls)),
    #url(r'^loginout/$', 'loginout',name='logout'),

    url(r'^$', index),
    url(r'^alarm_add',alarm_add),
    url(r'^data_sync',data_sync),
    url(r'^count',count),
    url(r'^dashboard',link),
    url(r'^admin/', admin.site.urls),
	]

leopard/models.py
# -*- coding: UTF-8 -*- 
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.

#多个svn对应一个host，外键应该在svn表里面
'''
       
class hosts(models.Model):
    host_name = models.CharField(max_length=30)
    host_user = models.CharField(max_length=30)
    host_pass = models.CharField(max_length=50)
    host_w_ip = models.IPAddressField()
    host_w_port = models.PositiveIntegerField(max_length=10)
    host_n_ip = models.IPAddressField()
    host_n_port = models.PositiveIntegerField(max_length=10)
    host_root_pwd = models.CharField(max_length=50)
    script_dir = models.CharField(max_length=100)
    host_description = models.TextField(blank=True)
    create_user = models.CharField(max_length=10)

    def __unicode__(self):
        return self.host_name


class svns(models.Model):
    svn_name = models.CharField(max_length=20)
    svn_user = models.CharField(max_length=30)
    svn_pass = models.CharField(max_length=30)
    svn_local = models.CharField(max_length=100)
    svn_path = models.CharField(max_length=100)
    #host  = models.ForeignKey(hosts,on_delete=models.SET_NULL())
    create_user = models.CharField(max_length=10)
    def __unicode__(self):
        return self.svn_name


class hostgroup(models.Model):
    host_groupname = models.CharField(max_length=30)
    host = models.ManyToManyField(hosts)
    create_date = models.CharField(max_length=30)
    create_user = models.CharField(max_length=10)
    
    def __unicode__(self):
        return self.host_groupname

class scripts(models.Model):
    script_name = models.CharField(max_length=30)
    script_file = models.FileField(upload_to='leopard/script/')
    script_date = models.CharField(max_length=50)
    script_description = models.TextField(blank=True)
    create_user = models.CharField(max_length=10)
    def __unicode__(self):
        return self.script_name

class scriptgroup(models.Model):
    script_groupname = models.CharField(max_length=30)
    script = models.ManyToManyField(scripts)
    create_date = models.CharField(max_length=30)
    create_user = models.CharField(max_length=10)
    def __unicode__(self):
        return self.script_groupname

class tasks(models.Model):
    task_name = models.CharField(max_length=50)
    #script_group = models.ForeignKey(scriptgroup)
    #host_group = models.ForeignKey(hostgroup)
    task_date = models.CharField(max_length=50)
    task_status = models.CharField(max_length=10)
    task_create_user = models.CharField(max_length=30)
    def __unicode__(self):
        return self.task_name

class services(models.Model):
    host  = models.ForeignKey(hosts)
    service_name = models.CharField(max_length=50)
    service_script = models.CharField(max_length=100)
    service_log = models.CharField(max_length=100)

    def __unicode__(self):
        return self.service_name

class releases(models.Model):
    create_user =  models.CharField(max_length=10)
    add_time = models.CharField(max_length=30)
    add_reason = models.TextField()
    start_test_time = models.CharField(max_length=30,blank=True)
    end_test_time = models.CharField(max_length=30,blank=True)
    test_status = models.CharField(max_length=1,default='3')
    upload_file = models.FileField(upload_to='leopard/packages/',max_length=100)
    ststus_reason = models.CharField(max_length=15,blank=True)

    def __unicode__(self):
        return self.id

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(u"姓名",max_length=30)
    iphone = models.CharField(u'手机',max_length=11)
'''

leopard/views.py
# -*- coding: UTF-8 -*- 
import sys

from django.shortcuts import render_to_response,render
from django.http import HttpResponse,HttpResponseRedirect
from django.db import models
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.forms.models import model_to_dict
from django.contrib.auth.models import User  
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as user_login, logout as user_logout
from django.shortcuts import render, render_to_response, Http404, get_object_or_404, RequestContext

from cloudwatch.create_alarm import create_cloudwatch_alarm
from cloudwatch.ec2_alarm_add import ec2_alarm
from cloudwatch.rds_alarm_add import rds_alarm as rds_alarm_create
from cloudwatch.elb_alarm_add import elb_alarm as elb_alarm_create
from cloudwatch.redis_alarm_add import redis_alarm as redis_alarm_create

from leopard.form import alarm_form,test_data_sync
from leopardproject import settings

from static.static import mapping
from tasks import restore_cache

#from data_sync.sync_redis_from_prod import restore_cache
#from function import *
#import restore_cache

#reload(sys)
#sys.setdefaultencoding("utf-8")

def index(request):
    return render_to_response('task.html')
'''
def alarm_add(request):
    if request.method == 'POST':
        form = alarm_form(request.POST)
        if form.is_valid():
            #selected_alarm_type = request.POST['alarm_type']
            selected_alarm_type = form.cleaned_data['alarm_type']
            identifier = form.cleaned_data['identifier']
            region = form.cleaned_data['region']
            if selected_alarm_type == 'ec2':
                try:    
                    alarm = ec2_alarm(identifier,region)
                    alarm.create_alarm_sets()
                    return HttpResponse('ok')
                except Exception, e:
                    return HttpResponse(e) 
            if selected_alarm_type == 'rds':
                try:
                    alarm = rds_alarm_create(identifier,region)
                    alarm.create_alarm_sets()
                    return HttpResponse('ok')
                except Exception, e:
                   return HttpResponse(e)
            if selected_alarm_type == 'elb':
                try:
                    alarm = elb_alarm_create(identifier,region)
                    alarm.create_alarm_sets()
                    return HttpResponse('ok')
                except Exception, e:
                   return HttpResponse(e)
            if selected_alarm_type == 'redis':
                try:
                    alarm = redis_alarm_create(identifier,region)
                    alarm.create_alarm_sets()
                    return HttpResponse('ok')
                except Exception, e:
                   return HttpResponse(e)
    else:      
        form = alarm_form()
    return render_to_response('alarm_add.html',{'alarm_add_form':form}) 
'''
def alarm_add(request):
    if request.method == 'POST':
        form = alarm_form(request.POST)
        if form.is_valid():
            #selected_alarm_type = request.POST['alarm_type']
            alarm_type = form.cleaned_data['alarm_type']
            identifier = form.cleaned_data['identifier']
            region = form.cleaned_data['region']
            try:
                create_cloudwatch_alarm(alarm_type,identifier,region)
                return HttpResponse('ok')
            except Exception, e:
                return HttpResponse(e)
    else:      
        form = alarm_form()
    return render_to_response('alarm_add.html',{'alarm_add_form':form}) 

def data_sync(request):
    if request.method == 'POST':
        form = test_data_sync(request.POST)
        if form.is_valid():
            cache_cluster_id = request.POST['cache_cluster_id']
            try:
                restore_cache.delay(cache_cluster_id)
            except Exception, e:
                return HttpResponse(e)
    else:
        form = test_data_sync()
    return render_to_response('data_sync.html',{'form':form})

def count(request):
    if request.method == 'POST':
        map = mapping() 
    return render_to_response('static.html')    
    
def link(request):
    return render_to_response('link.html')    

leopard/templates/addhostgroup.html
{% extends "base.html" %}
{% block title %}<title>Add Server Group</title>{% endblock %}
{% block content %}
<h3>Add Server Group</h3>
	<hr>
	<form method="POST" class="form-horizontal">
  <div class="control-group">
    <label class="control-label" for="host_name">Group Name:</label>
    <div class="controls">
      {{ form.host_groupname }}{{form.host_groupname.errors}}
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="host_w_ip">Host List:</label>
    <div class="controls">
      {{ form.host }}{{form.host.errors}}
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn" id="send" >Save Server Group</button>
    </div>
  </div>
</form>
{% endblock %}

leopard/templates/addservice.html
{% extends "base.html" %}
{% block title %}<title>Add service</title>{% endblock %}
{% block content %}
<h3>Add service</h3>
	<hr>
	<form method="POST" class="form-horizontal">
  <div class="control-group">
    <label class="control-label" for="service_name">service name:</label>
    <div class="controls">
     {{ form.service_name }}
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="service_script">service script:</label>
    <div class="controls">
     {{ form.service_script }}
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="service_log">service log:</label>
    <div class="controls">
     {{ form.service_log }}
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="service_host">service by Host:</label>
    <div class="controls">
	{{ form.host }}
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn" >Add service</button>
    </div>
  </div>
</form>
<span class="label label-success">{{result}}</span>
{% endblock %}

leopard/templates/adduser.html
{% extends "base.html" %}
{% block title %}<title>Add User</title>{% endblock %}
{% block content %}
<h3>Add User</h3>
	<hr>
	<form method="POST" class="form-horizontal">
  <div class="control-group">
    <label class="control-label" for="host_name">用户名:</label>
    <div class="controls">
      {{ form.username }}{{form.username.errors}}
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="host_w_ip">密码:</label>
    <div class="controls">
      {{ form.password }}{{form.password.errors}}
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="host_n_ip">姓名:</label>
    <div class="controls">
      <input id="id_xingming" type="text" name="xingming" maxlength="75" />
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="host_n_ip">手机:</label>
    <div class="controls">
      <input id="id_iphone" type="text" name="iphone" maxlength="75" />
    </div>
  </div>
  
    <div class="control-group">
    <label class="control-label" for="host_n_ip">邮箱:</label>
    <div class="controls">
      {{ form.email }}{{form.email.errors}}
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn" id="send" >Save User</button>
    </div>
  </div>
</form>
{% endblock %}

leopard/templates/alarm_add.html
{% extends "base.html" %}
{% block title %}<title>Add AWS Alarm</title>{% endblock %}
{% block content %}

<h4>Add Alarm</h4>
    <hr>
    <div>
        <form method='POST'>
            {% csrf_token %}
            {{alarm_add_form}}
            <div class="controls">
                <div class="controls">
                    <button type="submit" class="btn btn-primary" >create</button>
                </div>
            {{message}}
            </div>
        </form>  
    </div>
<!-- 模态框（Modal） -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
				&times;
                </button>
				<h4 class="modal-title" id="myModalLabel">
				    Message	
				</h4>
			</div>
			<div class="modal-body">
				文本{{ message }}
			</div>
			<div class="modal-footer">
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal -->
{% endblock %}

leopard/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    {% block title %}<title>leopard</title>{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
	 <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
     <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
 	 <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="#">运维平台</a>
		  <div class="nav-collapse collapse">
		  <ul class="nav pull-right">
			<li class="dropdown"> 
			<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i>  <b class="caret"></b></a>
			<ul class="dropdown-menu"> 
			<li><a href="#"><i class="icon-user"></i> 个人资料</a></li>
			<li class="divider"></li> 
			<li><a href="#"><i class="icon-off"></i> 注销</a></li> </ul> </li>
		  </ul>
		  </div>
        </div>
      </div>
    </div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <ul class="nav nav-tabs nav-stacked">

        <li><a href="#"><i class="icon-th"></i> Services</a></li>
		<li><a href="#"><i class="icon-lock"></i> Group</a></li>
		<li><a href="#"><i class="icon-lock"></i> Task</a></li>
		<li><a href="#"><i class="icon-lock"></i> User</a></li>
		<li><a href="/data_sync"><i class="icon-lock"></i> data_sync</a></li>
		<li><a href="/alarm_add"><i class="icon-lock"></i> Add Alarm</a></li>
		<li><a href="/count"><i class="icon-lock"></i>static</a></li>
		<li><a href="/dashboard"><i class="icon-lock"></i>link</a></li>

	  </ul>
    </div>
    <div class="box span10">
	
	{% block content %}{% endblock %}
	
    </div><!-- span 10 -->
  </div>
</div>
    <footer>
    </footer>
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.js"></script>
	<script src="/static/js/bootstrap.min.js"></script>
	
	<script src="/static/js/leopard.js"></script>
	<script type="text/javascript">
    function run_script(id,type,operation)
    {
        $.post("/showservice/",
        {
          id:id,
          type:type,
          operation:operation
        },
        function(data){
        $("#script_result").show()
        $("#script_result").html(data);
        });
    }
    function cat_log(id,operation){
        $.post("/showservice/",
        {
          id:id,
          operation:operation
        },
        function(data){
          $("#script_result").show()
          $("#script_result").html(data)
          $("#script_result").scrollTop($("#script_result").scrollHeight);
        });
        }
    function del_service(id,operation){
        $.post("/showservice/",
        {
          id:id,
          operation:operation
        },
        function(data){
            alert(data)
            window.location.reload();
        });
        }
    function ch_status(id,num){
        $.post("/showrelease/",
        {
           id:id,
           num:num
        },
        function(data){
            alert(data)
            window.location.reload();
        });
        }
    function ch_status_back(id,num){
        var reason=prompt("请输入打回原因:",'');
        if(reason){
        $.post("/showrelease/",
        {
           id:id,
           num:num,
           reason:reason
        },
        function(data){
            alert(data)
            window.location.reload();
        });}
        else if(reason==''){
            alert('请输入打回原因！');
            ch_status_back(id,num)
        }
        else if(reason==undefined){}
    }
  </script>
  </body>
</html>

leopard/templates/data_sync.html
{% extends "base.html" %}
{% block title %}<title>test data sync</title>{% endblock %}
{% block content %}

<h4>test data sync</h4>
    <hr>
    <div>
        <form method='POST'>
            {% csrf_token %}
            {% for field in form %}
               <P>{{ field.label_tag }}
                {{ field }}  
                {% for err in field.errors %}
                    <span style="color:red"> {{ err }} </span>
                {% endfor %}
          {% endfor %}    
        <div class="controls">
                <div class="controls">
                    <button type="submit" class="btn btn-primary" >提交</button>
                </div>
            </div>
        </form>  
    </div>
<!-- 模态框（Modal） -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
				&times;
                </button>
				<h4 class="modal-title" id="myModalLabel">
				    Message	
				</h4>
			</div>
			<div class="modal-body">
				文本{{ message }}
			</div>
			<div class="modal-footer">
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal -->
{% endblock %}

leopard/templates/delhost.html
{% extends "base.html" %}
{% block title %}<title>del Server</title>{% endblock %}
{% block content %}
			<div class="row-fluid sortable">	
				<div class="box span12">
					<div class="box-header well" data-original-title>
						<h5>确认删除服务器信息</h5>
						<p class="text-warning">删除服务器信息时，服务器上的svn信息也一并会删除！以下svn信息将被删除：</p>
					</div>
					<div class="box-content">
						<table class="table table-bordered table-striped table-condensed">
							  <thead>
								  <tr>
									  <th>所属服务器</th>
									  <th>本地路径</th>
									  <th>svn库路径</th>
									  <th>svn名称</th>  
								  </tr>
							  </thead>   
							  <tbody>
									{% for svn in svns %}
								<tr>
									<td>{{svn.host}}</td>
									<td>{{svn.svn_local}}</td>
									<td>{{svn.svn_path}}</td>
									<td class="center">{{svn.svn_name}}</td>    									
								</tr>   
									{% endfor %}
							  </tbody>
						 </table>  
					<a class="btn btn-primary" href="{% url leopard.views.confirm_del host_id %}"><i class="icon-trash"></i>点击确认删除服务器信息以及svn信息</a>
					</div>
				</div><!--/span-->
			</div><!--/row-->
{% endblock %}

leopard/templates/edituser.html
{% extends "base.html" %}
{% block title %}<title>Edit User</title>{% endblock %}
{% block content %}
<h3>Edit User</h3>
	<hr>
	<form method="POST" class="form-horizontal">
  <div class="control-group">
    <label class="control-label" for="host_name">用户名:</label>
    <div class="controls">
      <input id="id_username" class="disabled" type="text" name="username" maxlength="75" value="{{user.username}}" disabled />
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="host_w_ip">密码:</label>
    <div class="controls">
    <input id="id_password" type="text" name="password" maxlength="75" />
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="host_n_ip">姓名:</label>
    <div class="controls">
      <input id="id_xingming" type="text" name="xingming" maxlength="75" value="{{user.userprofile.name}}" />
    </div>
  </div>
    <div class="control-group">
    <label class="control-label" for="host_n_ip">手机:</label>
    <div class="controls">
      <input id="id_iphone" type="text" name="iphone" maxlength="75" value="{{user.userprofile.iphone}}" />
    </div>
  </div>
  
    <div class="control-group">
    <label class="control-label" for="host_n_ip">邮箱:</label>
    <div class="controls">
      <input id="id_email" type="text" name="email" maxlength="75" value="{{user.email}}" />
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn" id="send" >Save User</button>
    </div>
  </div>
</form>
{% endblock %}

leopard/templates/group.html
{% extends "base.html" %}
{% block title %}<title>Add Server Group</title>{% endblock %}
{% block content %}
<h3>Add Server Group</h3>
	<hr>
	<form class="well form-inline" method="POST" >
	  <div class="input-prepend">
	   <span class="add-on">Server Group Name</span>{{ host_group_form.host_groupname }}
	   </div>
	   <input type="hidden" name="grouptype" value="servergroup">
	  <button type="submit" class="btn btn-small btn-primary">Create New Server Group</button>
	</form>
      <table class="table table-bordered table-striped table-condensed">
		<thead>
			<tr>
			<th>Server Group Name</th>
			<th>Create Date</th>
			<th>Create User</th>
			<th>操作</th>
			</tr>
		</thead>
		<tbody>
			{% for hostgroup in hostgroups %}
			<tr>
			  <td><a href="{% url 'hostgroup_detail' hostgroup.id %}">{{hostgroup.host_groupname}}</a></td>
			  <td>{{hostgroup.create_date}}</td>
			  <td>{{hostgroup.create_user}}</td>
			  <td><a href="{% url 'hostgroup_del' hostgroup.id %}" title="Delete Server Group"><i class="icon-remove"></i></a></td>
			</tr>
			{% endfor %}
		</tbody>
	  </table>  	
	
	
  <h3>Add Script Group</h3>
  <hr>
	<form class="well form-inline" method="POST" >
	  <div class="input-prepend">
	   <span class="add-on">Script Group Name</span>{{ script_group_form.script_groupname }}
	   </div>
	   <input type="hidden" name="grouptype" value="scriptgroup">
	  <button type="submit" class="btn btn-small btn-primary">Create New Script Group</button>
	</form>
	      <table class="table table-bordered table-striped table-condensed">
		<thead>
			<tr>
			<th>Script Group Name</th>
			<th>Create Date</th>
			<th>Create User</th>
			<th>操作</th>
			</tr>
		</thead>
		<tbody>
			{% for scriptgroup in scriptgroups %}
			<tr>
			  <td><a href="{% url 'scriptgroup_detail' scriptgroup.id %}">{{scriptgroup.script_groupname}}</a></td>
			  <td>{{scriptgroup.create_date}}</td>
			  <td>{{scriptgroup.create_user}}</td>
			  <td><a href="{% url 'scriptgroup_del' scriptgroup.id %}" title="Delete Script Group"><i class="icon-remove"></i></a></td>
			</tr>
			{% endfor %}
		</tbody>
	  </table>  
{% endblock %}

leopard/templates/showhost_bak.html
{% extends "base.html" %}
{% block title %}<title>测试标题</title>{% endblock %}
{% block content %}
<div>
	<form class="form-search" method="POST">
	<input type="text" name ="search" class="input-medium search-query" placeholder="Search">
	<button type="submit" class="btn">Search</button>&nbsp;&nbsp;
	<a href="/hostadd"><span class="label label-warning">Add Server</span></a>&nbsp;&nbsp;
	<a href="#"><span class="label label-inverse">Del Server</span></a>
	</form>
</div>
	<hr>
      <table class="table table-bordered table-striped">
		<thead>
			<tr>
			<th>test</th>
			<th>test</th>
			<th>test</th>
			<th>test</th>
			<th>test</th>
			</tr>
		</thead>
		<tbody>
			<tr>
			<td><a href="#">asxsxsa</a></td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			</tr>
			<tr>
			<td>assa</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			</tr>
			<tr>
			<td>assa</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			</tr>
			<tr>
			<td>assa</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			</tr>
			<tr>
			<td>assa</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			</tr>
			<tr>
			<td>assa</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			</tr>
			<tr>
			<td>assa</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			</tr>
			<tr>
			<td>assa</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			</tr>
			<tr>
			<td>assa</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			</tr>
			<tr>
			<td>assa</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			</tr>
			<tr>
			<td>assa</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>sasasas</td>
			<td>
			<div class="btn-group">
			  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
			  Action
			<span class="caret"></span>
		   </a>
			<ul class="dropdown-menu">
			<li><a href="#" id="12" name="Edit" >Action</a></li>
			</ul>
		  </div>
			
			
			
			</td>
			</tr>
		</tbody>
	  </table>
	  <div class="pagination pagination-centered">
		<ul>
			<li><a href="#">前一页</a></li>
			<li class="active"><a href="#">1</a></li>
			<li><a href="#">2</a></li>
			<li><a href="#">3</a></li>
			<li><a href="#">4</a></li>
			<li><a href="#">后一页</a></li>
		</ul>
	  </div>
	  
	  <a class="btn" data-toggle="modal" href="#myModal"  data-keyboard="true" data-backdrop="static" >点击"无ESC关闭，无遮蔽背景"演示</a>
	  <div class="modal hide fade" id="myModal">
		<div class="modal-header">
			<a class="close" data-dismiss="modal">×</a>
		<h3>对话框标题</h3>
	  </div>
	  <div class="modal-body">
		<p>对话框内容</p>
	  </div>
	  <div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">关闭</a>
		<a href="#" class="btn btn-primary">保存更新</a>
	  </div>
	  </div>	
	  <br>
	 <button type="button" id="fat-btn" class="btn btn-primary" data-loading-text="Loading..." onclick="test()" >Loading state</button>
{% endblock %}

leopard/templates/static.html
{% extends "base.html" %}
{% block title %}<title></title>{% endblock %}
{% block content %}

<h4>资源统计</h4>
    <hr>
    <div>
        <form method='POST'>
            {% csrf_token %}
                <div class="controls">
                    <button type="submit" class="btn btn-primary" >update</button>
                </div>
            </div>
        </form>  
       <img src='static/img/ec_count.png' height="800" width="1200">
    </div>
{% endblock %}